name: parconc-examples
version: 0.0.1

tested-with: GHC==8.4.4

dependencies:
- base <5 && >=4
- containers >=0.4.0.0
- array >=0.4
- parallel
- time
- deepseq

source-dirs: src
ghc-options: -O2 -threaded -with-rtsopts=-N -eventlog

executables:
  rpar-exe:
    main: rpar.hs
  sudoku1-exe:
    source-dirs: src
    main: sudoku1.hs
  sudoku2-exe:
    source-dirs: src
    main: sudoku2.hs
  sudoku3-exe:
    source-dirs: src
    main: sudoku3.hs
